# -*- coding: utf-8 -*-
"""credentials.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qEK4HKN6bnUTHIhJ_BQP_2JJ2ZD1uXSx
"""

OPENAI_API_KEY="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"

